### ISSUE TITLE
PHP 8.1: Incompatibility with `IteratorAggregate::getIterator`

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-form#151]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | latest

#### Summary

The `Fieldset` implementation has an incompatibility with the `IteratorAggregate::getIterator`.

#### Current behavior

Tests are failing.
```
PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught Return type of Fieldset::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice``
```

#### How to reproduce

Execute tests with PHP 8.1

#### Expected behavior

Tests are passing.

**Comment by tobias-trozowski** [comment]
test fixed with https://github.com/laminas/laminas-form/pull/128

Bumping 
* `laminas/laminas-stdlib` to ^3.6.1
* `laminas/laminas-captcha` to ^2.11.0
* `laminas/laminas-session` to ^2.12.0 
* `phpunit/phpunit` to ^9.5.8 
will make the tests pass as long as dependencies installed with `--ignore-platform-req=php`.

dependencies not supporting php 8.1 right now
* `laminas/laminas-inputfilter`
* `laminas/laminas-recaptcha`
* `laminas/laminas-filter`

Would it make any sense to add `--ignore-platform-req=php` for php 8.1 as only dev-deps are affected?

**Comment by Ocramius** [comment]
Yes, see how other components already do that 👍
