### ISSUE TITLE
Fix 3.1.1 also for 2.17.0

### ISSUE THREAD

**Issue by panvid** [laminas/laminas-form#162]
### Feature Request

The urgend security issue which is released on https://github.com/laminas/laminas-form/releases/tag/3.1.1 should also be available older Minor and Major releases, like 3.0.* and 2.17.*

Right now only the 3.1.1 can be used without any security issue: https://github.com/Roave/SecurityAdvisories/blob/latest/composer.json#L161

**Comment by Ocramius** [comment]
That is intentional:

 * `laminas/laminas-form:2.17.0` supports `php:^7.3`, which is EOL and no longer covered by security fixes ( https://www.php.net/supported-versions.php )
 * `laminas/laminas-form:3.0.0` (released ~6mo ago) is `php:^7.4` (still covered by security fixes), and therefore receives security fixes
 * see our discussed policy about this at https://github.com/laminas/technical-steering-committee/blob/2cfa4a5a6609be81eab0e67cbc83c90633ad8c9f/meetings/minutes/2020-03-02-TSC-Minutes.md#lts-policy
   > A given minor release branch will continue to receive security backports until the minimum PHP version it supports is no longer supported by php.net.


As for upgrading, it doesn't seem to be too problematic:

 * https://github.com/laminas/laminas-form/blob/ed6c9722c2b3b3f8825b2ce626c8d0da29a72594/docs/book/v3/migration/v2-to-v3.md#migration-from-version-2-to-3

Dependencies were bumped too, so the biggest change is `s/Zend\Form\/Laminas\Form\` 
 * https://github.com/laminas/laminas-form/blob/2a18e6724739f3f1875d30a6bb8ecedb3da5242e/composer.json#L10-L22
 * https://github.com/laminas/laminas-form/blob/ed6c9722c2b3b3f8825b2ce626c8d0da29a72594/composer.json#L10-L24


Overall, I believe that the security on `3.x`-only is in line with policy, although @Slamdunk would probably see if having `2.18.0` is a sensible choice here.

**Comment by Slamdunk** [comment]
Given `v2` is still installed [10 times more](https://packagist.org/packages/laminas/laminas-form/stats) than `v3` and that back-porting seems straightforward, I'll provide a release for both `2.17` and `3.0`, but I need to accommodate my job duties first.
Any PR would be very welcome.

**Comment by Ocramius** [comment]
https://github.com/advisories/GHSA-jq4p-mq33-w375 will also require updating :|

**Comment by Slamdunk** [comment]
I guess I don't have the rights to do that, 'cause I see no edit button there nor in https://github.com/laminas/laminas-form/security/advisories/GHSA-jq4p-mq33-w375

Is updating a GH security advisor cumbersome?

**Comment by Ocramius** [comment]
Yes, we'd need to contact github support for doing that.

**Comment by Slamdunk** [comment]
@weierophinney what would you prefer me to do then?

**Comment by weierophinney** [comment]
I'm actually able to edit the security release (I have an "Edit" button, at least, when I view the page). If you want to backport the patches, @Slamdunk, I can update it after you've done so.

**Comment by Ocramius** [comment]
@weierophinney beware that the published advisory (under https://github.com/advisories ) is not the one under the repo :D

**Comment by weierophinney** [comment]
@Ocramius Oooooh. That's interesting.

We'll see what happens when I edit it, then. :)

**Comment by panvid** [comment]
Thanks for the reply :) So it sounds that there will be a fix for *2.17.x* too? :D
yeeah, nice

**Comment by Slamdunk** [comment]
@weierophinney `v2.17.1` and `v3.0.2` released with the bugfix, let's see how GHSA behave after your edit.

Also let's see if https://github.com/Roave/SecurityAdvisories/blob/latest/composer.json#L161 updates as well

**Comment by weierophinney** [comment]
I've edited our own version of the security advisory; let's see if GitHub picks up the updates.

**Comment by Slamdunk** [comment]
GHSA updated: https://github.com/advisories/GHSA-jq4p-mq33-w375

`Roave/SecurityAdvisories` updated as well: https://github.com/Roave/SecurityAdvisories/commit/fa60732bcafd446e9ff858eefa06cdcbae8d9823

:partying_face:

**Comment by Ocramius** [comment]
Awesome, and already reflected downstream: https://github.com/Roave/SecurityAdvisories/commit/fa60732bcafd446e9ff858eefa06cdcbae8d9823

**Comment by steffendietz** [comment]
Thanks for backporting this change.

@weierophinney could you maybe check https://github.com/advisories/GHSA-jq4p-mq33-w375? The patched version `2.17.2` should probably be `2.17.1` (also the affected version should probably be `< 2.17.1`), since this is currently picked up wrong by the https://github.com/Roave/SecurityAdvisories/commit/fa60732bcafd446e9ff858eefa06cdcbae8d9823.

Thanks a lot!

**Comment by weierophinney** [comment]
@steffendietz I did it incorrectly on my first submission, but corrected it within a minute or so; it's up-to-date on our own advisory page. Since they picked up the initial change, my guess is they'll pick up the second one shortly.

**Comment by steffendietz** [comment]
Ok, I understand. Let's wait and see, then. Thanks for the update. 👍

**Comment by panvid** [comment]
Thanks for the great work, guys!

**Comment by steffendietz** [comment]
The changes don't seem to get picked up. Maybe the advisory needs yo be edited again for GH to be triggered?

**Comment by Ocramius** [comment]
Similar/related: 

 * https://github.com/Roave/SecurityAdvisories/issues/90
 * https://twitter.com/Ocramius/status/1489146984363708418

**Comment by weierophinney** [comment]
I've pushed another update (I noticed we had references to `formRenderErrors()`, which should be `formElementErrors()`); let's see if they pick this one up.

**Comment by Slamdunk** [comment]
Still no update on https://github.com/advisories/GHSA-jq4p-mq33-w375

At this point we could easily release a `2.17.2` version just to match that GHSA, wdyt?

The older I get, the shorter the path I want to walk towards mental happiness

**Comment by Ocramius** [comment]
Meanwhile, manual workaround on `roave/security-advisories:dev-latest`.

See https://github.com/Roave/SecurityAdvisoriesBuilder/pull/528
See https://github.com/Roave/SecurityAdvisoriesBuilder/pull/530
See https://github.com/Roave/SecurityAdvisories/commit/2ec9ad634c459ee60c42d99390be37c8a3c6e8e5

**Comment by Ocramius** [comment]
> At this point we could easily release a `2.17.2` version just to match that GHSA, wdyt?

IMO OK - would just need to note the missing update on GitHub's side as the reason for an empty release (you can put it in the milestone description, then close the milestone for the release to happen - **should** work even with no PRs)

**Comment by Slamdunk** [comment]
> **should** work

Testing in production? Love it :sunglasses: 

I'll wait for another :seal: of approval on the idea, then I'll do it

**Comment by Ocramius** [comment]
> > **should** work
> 
> Testing in production? Love it sunglasses

Worst that can happen is that `laminas/automatic-releases` just fails to produce a tag, due to its strict invariants :)
